---
env:
  browser: true
  es6: true
  webextensions: true

ignorePatterns:
  - '*.scss'
  - '*.html'

overrides:
  - files:
      - '*.js'
    env:
      node: true
    extends:
      - '@matthiaskunnen/eslint-config-base'

  - files:
      - 'src/**/*.ts'
    parserOptions:
      project: tsconfig.lint.json
    extends:
      - '@matthiaskunnen/eslint-config-typescript'
    rules:
      no-console:
        - error
        - allow:
            - error
            - warn
